//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMarkerEntities : DbContext
    {
        public dbMarkerEntities()
            : base("name=dbMarkerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SQLITEADMIN_QUERIES> SQLITEADMIN_QUERIES { get; set; }
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblAccountGroup> tblAccountGroups { get; set; }
        public virtual DbSet<tblAccountOpeningBalance> tblAccountOpeningBalances { get; set; }
        public virtual DbSet<tblAccountVoucher> tblAccountVouchers { get; set; }
        public virtual DbSet<tblAccountVoucherDetaill> tblAccountVoucherDetaills { get; set; }
        public virtual DbSet<tblAdditionalItemMaster> tblAdditionalItemMasters { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblContraVoucher> tblContraVouchers { get; set; }
        public virtual DbSet<tblContraVoucherDetail> tblContraVoucherDetails { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCustomerBalance> tblCustomerBalances { get; set; }
        public virtual DbSet<tblCustomerOpBal> tblCustomerOpBals { get; set; }
        public virtual DbSet<tblDEMOGUID> tblDEMOGUIDs { get; set; }
        public virtual DbSet<tblFinPeriod> tblFinPeriods { get; set; }
        public virtual DbSet<tblGridLayout> tblGridLayouts { get; set; }
        public virtual DbSet<tblInvoicePrintFormat> tblInvoicePrintFormats { get; set; }
        public virtual DbSet<tblJournalVoucher> tblJournalVouchers { get; set; }
        public virtual DbSet<tblJournalVoucherDetail> tblJournalVoucherDetails { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblPriceList> tblPriceLists { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProductFormula> tblProductFormulas { get; set; }
        public virtual DbSet<tblProductFormulaDetail> tblProductFormulaDetails { get; set; }
        public virtual DbSet<tblProductStock> tblProductStocks { get; set; }
        public virtual DbSet<tblProductTaxCategory> tblProductTaxCategories { get; set; }
        public virtual DbSet<tblPurchaseBill> tblPurchaseBills { get; set; }
        public virtual DbSet<tblPurchaseBillAdditional> tblPurchaseBillAdditionals { get; set; }
        public virtual DbSet<tblPurchaseBillProductDetail> tblPurchaseBillProductDetails { get; set; }
        public virtual DbSet<tblPurchaseReceiptNoPrefix> tblPurchaseReceiptNoPrefixes { get; set; }
        public virtual DbSet<tblPurchaseReturn> tblPurchaseReturns { get; set; }
        public virtual DbSet<tblPurchaseReturnAdditional> tblPurchaseReturnAdditionals { get; set; }
        public virtual DbSet<tblPurchaseReturnNoPrefix> tblPurchaseReturnNoPrefixes { get; set; }
        public virtual DbSet<tblPurchaseReturnProductDetail> tblPurchaseReturnProductDetails { get; set; }
        public virtual DbSet<tblRate> tblRates { get; set; }
        public virtual DbSet<tblReceipt> tblReceipts { get; set; }
        public virtual DbSet<tblReceiptNoPrefix> tblReceiptNoPrefixes { get; set; }
        public virtual DbSet<tblSaleInvoice> tblSaleInvoices { get; set; }
        public virtual DbSet<tblSaleInvoiceAdditional> tblSaleInvoiceAdditionals { get; set; }
        public virtual DbSet<tblSaleInvoiceNoPrefix> tblSaleInvoiceNoPrefixes { get; set; }
        public virtual DbSet<tblSaleInvoiceProductDetail> tblSaleInvoiceProductDetails { get; set; }
        public virtual DbSet<tblSaleOrder> tblSaleOrders { get; set; }
        public virtual DbSet<tblSaleOrderAdditional> tblSaleOrderAdditionals { get; set; }
        public virtual DbSet<tblSaleOrderNoPrefix> tblSaleOrderNoPrefixes { get; set; }
        public virtual DbSet<tblSaleOrderProductDetail> tblSaleOrderProductDetails { get; set; }
        public virtual DbSet<tblSaleReturn> tblSaleReturns { get; set; }
        public virtual DbSet<tblSaleReturnAdditional> tblSaleReturnAdditionals { get; set; }
        public virtual DbSet<tblSaleReturnNoPrefix> tblSaleReturnNoPrefixes { get; set; }
        public virtual DbSet<tblSaleReturnProductDetail> tblSaleReturnProductDetails { get; set; }
        public virtual DbSet<tblSettingL0> tblSettingL0 { get; set; }
        public virtual DbSet<tblSettingMasterL1> tblSettingMasterL1 { get; set; }
        public virtual DbSet<tblSettingsL1> tblSettingsL1 { get; set; }
        public virtual DbSet<tblSMSLog> tblSMSLogs { get; set; }
        public virtual DbSet<tblSoftwareRegistration> tblSoftwareRegistrations { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
        public virtual DbSet<tblStockPDetail> tblStockPDetails { get; set; }
        public virtual DbSet<tblStockVoucherType> tblStockVoucherTypes { get; set; }
        public virtual DbSet<tblTransport> tblTransports { get; set; }
        public virtual DbSet<tblUnit> tblUnits { get; set; }
        public virtual DbSet<tblUpdateScriptLog> tblUpdateScriptLogs { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserGroup> tblUserGroups { get; set; }
        public virtual DbSet<tblUserGroupPerimission> tblUserGroupPerimissions { get; set; }
        public virtual DbSet<tblVoucherType> tblVoucherTypes { get; set; }
    }
}
