//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountOpeningBalance
    {
        public long AccountOpeningBalanceID { get; set; }
        public long AccountID { get; set; }
        public decimal OpeningBalanceAmount { get; set; }
        public long FinPeriodID { get; set; }
        public byte rstate { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<long> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
    }
}
