//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccountVoucher()
        {
            this.tblAccountVoucherDetaills = new HashSet<tblAccountVoucherDetaill>();
            this.tblContraVouchers = new HashSet<tblContraVoucher>();
            this.tblJournalVouchers = new HashSet<tblJournalVoucher>();
            this.tblPayments = new HashSet<tblPayment>();
            this.tblPurchaseBills = new HashSet<tblPurchaseBill>();
            this.tblPurchaseReturns = new HashSet<tblPurchaseReturn>();
            this.tblReceipts = new HashSet<tblReceipt>();
            this.tblSaleInvoices = new HashSet<tblSaleInvoice>();
            this.tblSaleReturns = new HashSet<tblSaleReturn>();
        }
    
        public long AccountVoucherID { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string VoucherNo { get; set; }
        public long VoucherTypeID { get; set; }
        public long FinPeriodID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> CustomerAccountID { get; set; }
        public Nullable<long> BookAccountID { get; set; }
        public byte rstate { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<long> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public string Narration { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblAccount tblAccount1 { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountVoucherDetaill> tblAccountVoucherDetaills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContraVoucher> tblContraVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJournalVoucher> tblJournalVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBill> tblPurchaseBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturn> tblPurchaseReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceipt> tblReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoice> tblSaleInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturn> tblSaleReturns { get; set; }
    }
}
