//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountVoucherDetaill
    {
        public long AccountVoucherDetailID { get; set; }
        public long AccountVoucherID { get; set; }
        public long AccountID { get; set; }
        public decimal Amount { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblAccountVoucher tblAccountVoucher { get; set; }
    }
}
