//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccount()
        {
            this.tblAccountOpeningBalances = new HashSet<tblAccountOpeningBalance>();
            this.tblAccountVouchers = new HashSet<tblAccountVoucher>();
            this.tblAccountVouchers1 = new HashSet<tblAccountVoucher>();
            this.tblAccountVoucherDetaills = new HashSet<tblAccountVoucherDetaill>();
            this.tblAdditionalItemMasters = new HashSet<tblAdditionalItemMaster>();
            this.tblContraVoucherDetails = new HashSet<tblContraVoucherDetail>();
            this.tblJournalVoucherDetails = new HashSet<tblJournalVoucherDetail>();
            this.tblPayments = new HashSet<tblPayment>();
            this.tblPayments1 = new HashSet<tblPayment>();
            this.tblPurchaseBills = new HashSet<tblPurchaseBill>();
            this.tblPurchaseBills1 = new HashSet<tblPurchaseBill>();
            this.tblPurchaseReturns = new HashSet<tblPurchaseReturn>();
            this.tblPurchaseReturns1 = new HashSet<tblPurchaseReturn>();
            this.tblReceipts = new HashSet<tblReceipt>();
            this.tblReceipts1 = new HashSet<tblReceipt>();
            this.tblSaleInvoices = new HashSet<tblSaleInvoice>();
            this.tblSaleInvoices1 = new HashSet<tblSaleInvoice>();
            this.tblSaleReturns = new HashSet<tblSaleReturn>();
            this.tblSaleReturns1 = new HashSet<tblSaleReturn>();
        }
    
        public long AccountID { get; set; }
        public long AccountNo { get; set; }
        public string AccountName { get; set; }
        public long AccountGroupID { get; set; }
        public Nullable<bool> DefaultAccount { get; set; }
        public long CompanyID { get; set; }
        public decimal BalanceAmt { get; set; }
        public string Address { get; set; }
        public Nullable<long> CityID { get; set; }
        public string PostCode { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string EMailID { get; set; }
        public string Website { get; set; }
        public string PAN { get; set; }
        public string GSTNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<long> CreditDays { get; set; }
        public Nullable<long> PriceListID { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<bool> AllowSendSMS { get; set; }
        public byte rstate { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<long> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblPriceList tblPriceList { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblAccountGroup tblAccountGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountOpeningBalance> tblAccountOpeningBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountVoucher> tblAccountVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountVoucher> tblAccountVouchers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountVoucherDetaill> tblAccountVoucherDetaills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdditionalItemMaster> tblAdditionalItemMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContraVoucherDetail> tblContraVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJournalVoucherDetail> tblJournalVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBill> tblPurchaseBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBill> tblPurchaseBills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturn> tblPurchaseReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturn> tblPurchaseReturns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceipt> tblReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceipt> tblReceipts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoice> tblSaleInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoice> tblSaleInvoices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturn> tblSaleReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturn> tblSaleReturns1 { get; set; }
    }
}
