//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdditionalItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdditionalItemMaster()
        {
            this.tblProducts = new HashSet<tblProduct>();
            this.tblProducts1 = new HashSet<tblProduct>();
            this.tblProducts2 = new HashSet<tblProduct>();
            this.tblPurchaseBills = new HashSet<tblPurchaseBill>();
            this.tblPurchaseBillAdditionals = new HashSet<tblPurchaseBillAdditional>();
            this.tblPurchaseBillProductDetails = new HashSet<tblPurchaseBillProductDetail>();
            this.tblPurchaseBillProductDetails1 = new HashSet<tblPurchaseBillProductDetail>();
            this.tblPurchaseBillProductDetails2 = new HashSet<tblPurchaseBillProductDetail>();
            this.tblPurchaseReturns = new HashSet<tblPurchaseReturn>();
            this.tblPurchaseReturnAdditionals = new HashSet<tblPurchaseReturnAdditional>();
            this.tblPurchaseReturnProductDetails = new HashSet<tblPurchaseReturnProductDetail>();
            this.tblPurchaseReturnProductDetails1 = new HashSet<tblPurchaseReturnProductDetail>();
            this.tblPurchaseReturnProductDetails2 = new HashSet<tblPurchaseReturnProductDetail>();
            this.tblSaleInvoices = new HashSet<tblSaleInvoice>();
            this.tblSaleInvoiceAdditionals = new HashSet<tblSaleInvoiceAdditional>();
            this.tblSaleInvoiceProductDetails = new HashSet<tblSaleInvoiceProductDetail>();
            this.tblSaleInvoiceProductDetails1 = new HashSet<tblSaleInvoiceProductDetail>();
            this.tblSaleInvoiceProductDetails2 = new HashSet<tblSaleInvoiceProductDetail>();
            this.tblSaleOrders = new HashSet<tblSaleOrder>();
            this.tblSaleOrderAdditionals = new HashSet<tblSaleOrderAdditional>();
            this.tblSaleOrderProductDetails = new HashSet<tblSaleOrderProductDetail>();
            this.tblSaleOrderProductDetails1 = new HashSet<tblSaleOrderProductDetail>();
            this.tblSaleOrderProductDetails2 = new HashSet<tblSaleOrderProductDetail>();
            this.tblSaleReturns = new HashSet<tblSaleReturn>();
            this.tblSaleReturnAdditionals = new HashSet<tblSaleReturnAdditional>();
            this.tblSaleReturnProductDetails = new HashSet<tblSaleReturnProductDetail>();
            this.tblSaleReturnProductDetails1 = new HashSet<tblSaleReturnProductDetail>();
            this.tblSaleReturnProductDetails2 = new HashSet<tblSaleReturnProductDetail>();
        }
    
        public long AdditionaItemID { get; set; }
        public string ItemName { get; set; }
        public int Nature { get; set; }
        public long CompanyID { get; set; }
        public int SystemRecord { get; set; }
        public int ItemType { get; set; }
        public decimal Perc { get; set; }
        public Nullable<bool> CalculatePerc { get; set; }
        public int CalculateOnID { get; set; }
        public Nullable<bool> IsInclusive { get; set; }
        public Nullable<bool> DefaultRecord { get; set; }
        public Nullable<int> DefaultRecordPrt { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<long> reuid { get; set; }
        public Nullable<long> ProductTaxCategoryID { get; set; }
        public byte rstate { get; set; }
        public Nullable<long> AccountID { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblProductTaxCategory tblProductTaxCategory { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBill> tblPurchaseBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBillAdditional> tblPurchaseBillAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBillProductDetail> tblPurchaseBillProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBillProductDetail> tblPurchaseBillProductDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBillProductDetail> tblPurchaseBillProductDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturn> tblPurchaseReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturnAdditional> tblPurchaseReturnAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturnProductDetail> tblPurchaseReturnProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturnProductDetail> tblPurchaseReturnProductDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturnProductDetail> tblPurchaseReturnProductDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoice> tblSaleInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceAdditional> tblSaleInvoiceAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceProductDetail> tblSaleInvoiceProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceProductDetail> tblSaleInvoiceProductDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceProductDetail> tblSaleInvoiceProductDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrder> tblSaleOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderAdditional> tblSaleOrderAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderProductDetail> tblSaleOrderProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderProductDetail> tblSaleOrderProductDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderProductDetail> tblSaleOrderProductDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturn> tblSaleReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnAdditional> tblSaleReturnAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnProductDetail> tblSaleReturnProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnProductDetail> tblSaleReturnProductDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnProductDetail> tblSaleReturnProductDetails2 { get; set; }
    }
}
