//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompany()
        {
            this.tblAccounts = new HashSet<tblAccount>();
            this.tblAccountGroups = new HashSet<tblAccountGroup>();
            this.tblAdditionalItemMasters = new HashSet<tblAdditionalItemMaster>();
            this.tblContraVouchers = new HashSet<tblContraVoucher>();
            this.tblCustomers = new HashSet<tblCustomer>();
            this.tblCustomerBalances = new HashSet<tblCustomerBalance>();
            this.tblCustomerOpBals = new HashSet<tblCustomerOpBal>();
            this.tblFinPeriods = new HashSet<tblFinPeriod>();
            this.tblGridLayouts = new HashSet<tblGridLayout>();
            this.tblJournalVouchers = new HashSet<tblJournalVoucher>();
            this.tblPayments = new HashSet<tblPayment>();
            this.tblPriceLists = new HashSet<tblPriceList>();
            this.tblProducts = new HashSet<tblProduct>();
            this.tblProductFormulas = new HashSet<tblProductFormula>();
            this.tblProductStocks = new HashSet<tblProductStock>();
            this.tblProductTaxCategories = new HashSet<tblProductTaxCategory>();
            this.tblPurchaseBills = new HashSet<tblPurchaseBill>();
            this.tblPurchaseBillProductDetails = new HashSet<tblPurchaseBillProductDetail>();
            this.tblPurchaseReceiptNoPrefixes = new HashSet<tblPurchaseReceiptNoPrefix>();
            this.tblPurchaseReturns = new HashSet<tblPurchaseReturn>();
            this.tblPurchaseReturnNoPrefixes = new HashSet<tblPurchaseReturnNoPrefix>();
            this.tblPurchaseReturnProductDetails = new HashSet<tblPurchaseReturnProductDetail>();
            this.tblRates = new HashSet<tblRate>();
            this.tblReceipts = new HashSet<tblReceipt>();
            this.tblReceiptNoPrefixes = new HashSet<tblReceiptNoPrefix>();
            this.tblSaleInvoices = new HashSet<tblSaleInvoice>();
            this.tblSaleInvoiceNoPrefixes = new HashSet<tblSaleInvoiceNoPrefix>();
            this.tblSaleInvoiceProductDetails = new HashSet<tblSaleInvoiceProductDetail>();
            this.tblSaleOrders = new HashSet<tblSaleOrder>();
            this.tblSaleOrderNoPrefixes = new HashSet<tblSaleOrderNoPrefix>();
            this.tblSaleOrderProductDetails = new HashSet<tblSaleOrderProductDetail>();
            this.tblSaleReturns = new HashSet<tblSaleReturn>();
            this.tblSaleReturnNoPrefixes = new HashSet<tblSaleReturnNoPrefix>();
            this.tblSaleReturnProductDetails = new HashSet<tblSaleReturnProductDetail>();
            this.tblSettingsL1 = new HashSet<tblSettingsL1>();
            this.tblStocks = new HashSet<tblStock>();
            this.tblTransports = new HashSet<tblTransport>();
            this.tblVoucherTypes = new HashSet<tblVoucherType>();
        }
    
        public long CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public long CityID { get; set; }
        public string PIN { get; set; }
        public string Phone1 { get; set; }
        public string MobileNo1 { get; set; }
        public string EMailID { get; set; }
        public string Website { get; set; }
        public string PAN { get; set; }
        public string GSTIN { get; set; }
        public string LicenseName { get; set; }
        public string LicenseNo { get; set; }
        public string Jurisdiction { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public System.DateTime BusinessStartedFrom { get; set; }
        public string DirectorName { get; set; }
        public string ServiceTaxNo { get; set; }
        public string BankName { get; set; }
        public string BankCity { get; set; }
        public string BankBranch { get; set; }
        public string BankIFSC { get; set; }
        public string BankAccountNo { get; set; }
        public string BankAccountName { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<long> reuid { get; set; }
        public byte rstate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccount> tblAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountGroup> tblAccountGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdditionalItemMaster> tblAdditionalItemMasters { get; set; }
        public virtual tblCity tblCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContraVoucher> tblContraVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomer> tblCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerBalance> tblCustomerBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerOpBal> tblCustomerOpBals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFinPeriod> tblFinPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGridLayout> tblGridLayouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJournalVoucher> tblJournalVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPriceList> tblPriceLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductFormula> tblProductFormulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductStock> tblProductStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductTaxCategory> tblProductTaxCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBill> tblPurchaseBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBillProductDetail> tblPurchaseBillProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReceiptNoPrefix> tblPurchaseReceiptNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturn> tblPurchaseReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturnNoPrefix> tblPurchaseReturnNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturnProductDetail> tblPurchaseReturnProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRate> tblRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceipt> tblReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceiptNoPrefix> tblReceiptNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoice> tblSaleInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceNoPrefix> tblSaleInvoiceNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceProductDetail> tblSaleInvoiceProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrder> tblSaleOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderNoPrefix> tblSaleOrderNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderProductDetail> tblSaleOrderProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturn> tblSaleReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnNoPrefix> tblSaleReturnNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnProductDetail> tblSaleReturnProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSettingsL1> tblSettingsL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStock> tblStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransport> tblTransports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherType> tblVoucherTypes { get; set; }
    }
}
