//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContraVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContraVoucher()
        {
            this.tblContraVoucherDetails = new HashSet<tblContraVoucherDetail>();
        }
    
        public long ContraVoucherID { get; set; }
        public int ContraVoucherNo { get; set; }
        public System.DateTime ContraVoucherDate { get; set; }
        public decimal Amount { get; set; }
        public string Narration { get; set; }
        public long CompanyID { get; set; }
        public long AccountVoucherID { get; set; }
        public long VoucherTypeID { get; set; }
        public byte rstate { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<long> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblAccountVoucher tblAccountVoucher { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContraVoucherDetail> tblContraVoucherDetails { get; set; }
    }
}
