//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblCustomerBalances = new HashSet<tblCustomerBalance>();
            this.tblSaleOrders = new HashSet<tblSaleOrder>();
        }
    
        public long CustomerID { get; set; }
        public long CustomerNo { get; set; }
        public string NameTitle { get; set; }
        public string CustomerName { get; set; }
        public decimal BalanceAmt { get; set; }
        public string Address { get; set; }
        public long CityID { get; set; }
        public string PostCode { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string EMailID { get; set; }
        public string Website { get; set; }
        public string PAN { get; set; }
        public string GSTNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public decimal CreditLimit { get; set; }
        public long CreditDays { get; set; }
        public Nullable<long> PriceListID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public long CompanyID { get; set; }
        public string CustomerCompanyName { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<long> reuid { get; set; }
        public Nullable<bool> AllowSendSMS { get; set; }
        public byte rstate { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblPriceList tblPriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerBalance> tblCustomerBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrder> tblSaleOrders { get; set; }
    }
}
