//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContraVoucherDetail
    {
        public long ContraVoucherDetailID { get; set; }
        public long ContraVoucherID { get; set; }
        public long AccountID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblContraVoucher tblContraVoucher { get; set; }
    }
}
