//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductTaxCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductTaxCategory()
        {
            this.tblAdditionalItemMasters = new HashSet<tblAdditionalItemMaster>();
        }
    
        public long ProductTaxCategoryID { get; set; }
        public string ProductTaxCategoryName { get; set; }
        public Nullable<bool> IsInterstateSale { get; set; }
        public int TaxIndex { get; set; }
        public bool Applicable { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<long> reuid { get; set; }
        public byte rstate { get; set; }
        public long CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdditionalItemMaster> tblAdditionalItemMasters { get; set; }
        public virtual tblCompany tblCompany { get; set; }
    }
}
