//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblProductFormulas = new HashSet<tblProductFormula>();
            this.tblProductFormulaDetails = new HashSet<tblProductFormulaDetail>();
            this.tblProductStocks = new HashSet<tblProductStock>();
            this.tblPurchaseBillProductDetails = new HashSet<tblPurchaseBillProductDetail>();
            this.tblPurchaseReturnProductDetails = new HashSet<tblPurchaseReturnProductDetail>();
            this.tblRates = new HashSet<tblRate>();
            this.tblSaleInvoiceProductDetails = new HashSet<tblSaleInvoiceProductDetail>();
            this.tblSaleOrderProductDetails = new HashSet<tblSaleOrderProductDetail>();
            this.tblSaleReturnProductDetails = new HashSet<tblSaleReturnProductDetail>();
            this.tblStocks = new HashSet<tblStock>();
            this.tblStockPDetails = new HashSet<tblStockPDetail>();
        }
    
        public long ProductID { get; set; }
        public long PCode { get; set; }
        public string Barcode { get; set; }
        public string HSNCode { get; set; }
        public string ProductName { get; set; }
        public string ProdDescr { get; set; }
        public Nullable<long> Tax1ID { get; set; }
        public Nullable<long> Tax2ID { get; set; }
        public Nullable<long> Tax3ID { get; set; }
        public long UnitID { get; set; }
        public decimal PurchaseRate { get; set; }
        public long CompanyID { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<long> reuid { get; set; }
        public byte rstate { get; set; }
    
        public virtual tblAdditionalItemMaster tblAdditionalItemMaster { get; set; }
        public virtual tblAdditionalItemMaster tblAdditionalItemMaster1 { get; set; }
        public virtual tblAdditionalItemMaster tblAdditionalItemMaster2 { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblUnit tblUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductFormula> tblProductFormulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductFormulaDetail> tblProductFormulaDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductStock> tblProductStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBillProductDetail> tblPurchaseBillProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseReturnProductDetail> tblPurchaseReturnProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRate> tblRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceProductDetail> tblSaleInvoiceProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderProductDetail> tblSaleOrderProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnProductDetail> tblSaleReturnProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStock> tblStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockPDetail> tblStockPDetails { get; set; }
    }
}
