//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductFormulaDetail
    {
        public long ProductFormulaDetailID { get; set; }
        public long ProductFormulaID { get; set; }
        public long RawMaterialProductID { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblProductFormula tblProductFormula { get; set; }
    }
}
