//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductFormula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductFormula()
        {
            this.tblProductFormulaDetails = new HashSet<tblProductFormulaDetail>();
        }
    
        public long ProductFormulaID { get; set; }
        public Nullable<System.DateTime> WEDate { get; set; }
        public long ProductID { get; set; }
        public decimal FinishQuantity { get; set; }
        public string Remark { get; set; }
        public long CompanyID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<long> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductFormulaDetail> tblProductFormulaDetails { get; set; }
    }
}
