//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRate
    {
        public long RateID { get; set; }
        public long ProductID { get; set; }
        public long PriceListID { get; set; }
        public decimal Rate { get; set; }
        public decimal DiscPerc { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<long> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblPriceList tblPriceList { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
