//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSaleReturn()
        {
            this.tblSaleReturnAdditionals = new HashSet<tblSaleReturnAdditional>();
            this.tblSaleReturnProductDetails = new HashSet<tblSaleReturnProductDetail>();
        }
    
        public long SaleReturnID { get; set; }
        public System.DateTime SaleReturnDate { get; set; }
        public Nullable<long> SaleReturnNoPrefixID { get; set; }
        public long SaleReturnNo { get; set; }
        public long CustomerAccountID { get; set; }
        public long SaleAccountID { get; set; }
        public long VoucherTypeID { get; set; }
        public long AccountVoucherID { get; set; }
        public long PriceListID { get; set; }
        public decimal GrossAmt { get; set; }
        public decimal NetAmt { get; set; }
        public string SaleReturnMemo { get; set; }
        public long CompanyID { get; set; }
        public long FinPeriodID { get; set; }
        public int MemoType { get; set; }
        public Nullable<long> StockVoucherID { get; set; }
        public Nullable<decimal> RoundOffAmt { get; set; }
        public Nullable<long> RoundOffAddLessID { get; set; }
        public byte rstate { get; set; }
        public Nullable<long> rcuid { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<long> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblAccount tblAccount1 { get; set; }
        public virtual tblAccountVoucher tblAccountVoucher { get; set; }
        public virtual tblAdditionalItemMaster tblAdditionalItemMaster { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        public virtual tblPriceList tblPriceList { get; set; }
        public virtual tblStock tblStock { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        public virtual tblSaleReturnNoPrefix tblSaleReturnNoPrefix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnAdditional> tblSaleReturnAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleReturnProductDetail> tblSaleReturnProductDetails { get; set; }
    }
}
