//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSaleInvoice()
        {
            this.tblSaleInvoiceAdditionals = new HashSet<tblSaleInvoiceAdditional>();
            this.tblSaleInvoiceProductDetails = new HashSet<tblSaleInvoiceProductDetail>();
            this.tblSaleOrders = new HashSet<tblSaleOrder>();
        }
    
        public long SaleInvoiceID { get; set; }
        public System.DateTime SaleInvoiceDate { get; set; }
        public long SaleInvoiceNo { get; set; }
        public Nullable<long> SaleInvoiceNoPrefixID { get; set; }
        public long CustomerAccountID { get; set; }
        public long SaleAccountID { get; set; }
        public long VoucherTypeID { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string SupplRefNo { get; set; }
        public string OtherRefNo { get; set; }
        public Nullable<long> TransportID { get; set; }
        public string NofPackets { get; set; }
        public string Destination { get; set; }
        public string DispDocNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public long PriceListID { get; set; }
        public decimal GrossAmt { get; set; }
        public decimal NetAmt { get; set; }
        public string InvoiceMemo { get; set; }
        public long CompanyID { get; set; }
        public long FinPeriodID { get; set; }
        public int MemoType { get; set; }
        public Nullable<long> StockVoucherID { get; set; }
        public Nullable<decimal> AdvanceAmt { get; set; }
        public Nullable<long> AdvanceRecieptID { get; set; }
        public Nullable<long> SaleOrderID { get; set; }
        public Nullable<decimal> RoundOffAmt { get; set; }
        public Nullable<long> RoundOffAddLessID { get; set; }
        public long AccountVoucherID { get; set; }
        public byte rstate { get; set; }
        public Nullable<long> rcuid { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<long> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblAccount tblAccount1 { get; set; }
        public virtual tblAccountVoucher tblAccountVoucher { get; set; }
        public virtual tblAdditionalItemMaster tblAdditionalItemMaster { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        public virtual tblPriceList tblPriceList { get; set; }
        public virtual tblReceipt tblReceipt { get; set; }
        public virtual tblSaleInvoiceNoPrefix tblSaleInvoiceNoPrefix { get; set; }
        public virtual tblSaleOrder tblSaleOrder { get; set; }
        public virtual tblStock tblStock { get; set; }
        public virtual tblTransport tblTransport { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceAdditional> tblSaleInvoiceAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoiceProductDetail> tblSaleInvoiceProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrder> tblSaleOrders { get; set; }
    }
}
