//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSettingL0
    {
        public long SettingL0ID { get; set; }
        public string SettingName { get; set; }
        public int SettingValueType { get; set; }
        public string SettingValueVC { get; set; }
        public Nullable<int> SettingValueInt { get; set; }
        public Nullable<long> SettingValueLong { get; set; }
        public Nullable<System.DateTime> SettingValueDateTime { get; set; }
        public Nullable<bool> SettingValueBoolean { get; set; }
        public Nullable<decimal> SettingValueDecimal { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<long> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<long> reuid { get; set; }
    }
}
