//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSaleOrder()
        {
            this.tblSaleInvoices = new HashSet<tblSaleInvoice>();
            this.tblSaleOrderAdditionals = new HashSet<tblSaleOrderAdditional>();
            this.tblSaleOrderProductDetails = new HashSet<tblSaleOrderProductDetail>();
        }
    
        public long SaleOrderID { get; set; }
        public System.DateTime SaleOrderDate { get; set; }
        public long SaleOrderNo { get; set; }
        public Nullable<long> SaleOrderNoPrefixID { get; set; }
        public long CustomerID { get; set; }
        public long PriceListID { get; set; }
        public decimal GrossAmt { get; set; }
        public decimal NetAmt { get; set; }
        public string OrderMemo { get; set; }
        public long CompanyID { get; set; }
        public long FinPeriodID { get; set; }
        public Nullable<long> SaleInvoiceID { get; set; }
        public Nullable<decimal> RoundOffAmt { get; set; }
        public Nullable<long> RoundOffAddLessID { get; set; }
        public byte rstate { get; set; }
        public Nullable<long> rcuid { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<long> reuid { get; set; }
    
        public virtual tblAdditionalItemMaster tblAdditionalItemMaster { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        public virtual tblPriceList tblPriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleInvoice> tblSaleInvoices { get; set; }
        public virtual tblSaleInvoice tblSaleInvoice { get; set; }
        public virtual tblSaleOrderNoPrefix tblSaleOrderNoPrefix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderAdditional> tblSaleOrderAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleOrderProductDetail> tblSaleOrderProductDetails { get; set; }
    }
}
