//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSMSLog
    {
        public long SMSLogID { get; set; }
        public string OptionName { get; set; }
        public string MobileNo { get; set; }
        public string SMSText { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
        public string DeliveryStatus { get; set; }
        public string SenderID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Error { get; set; }
        public string SMSID { get; set; }
        public string SMSAPIResponse { get; set; }
    }
}
