//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUpdateScriptLog
    {
        public long UpdateScriptID { get; set; }
        public bool Executed { get; set; }
        public System.DateTime ExecutionDateTime { get; set; }
    }
}
