
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Alit.Marker.DBO
{

using System;
    using System.Collections.Generic;
    
public partial class tblVoucherNoSery
{

    public long VoucherSeriesID { get; set; }

    public long VoucherTypeID { get; set; }

    public Nullable<System.DateTime> EffectiveFrom { get; set; }

    public Nullable<System.DateTime> EffectiveUpto { get; set; }

    public bool AutoGenerateVocuherNo { get; set; }

    public bool AllowEditVoucherNo { get; set; }

    public bool TabStopOnVocuherNo { get; set; }

    public bool AllowDuplicateVoucherNo { get; set; }

    public bool AutoGenerateVoucherNoOnDuplicateWhileSaving { get; set; }

    public bool AddPrefix { get; set; }

    public bool AddSuffix { get; set; }

    public int VoucheNoLengthInText { get; set; }

    public bool ResetAfterDelete { get; set; }

    public string Prefix { get; set; }

    public string Suffix { get; set; }

    public long InitialVoucherNo { get; set; }

    public long CompanyID { get; set; }

    public byte rstate { get; set; }

    public Nullable<long> reuid { get; set; }

    public Nullable<System.DateTime> rcdt { get; set; }

    public Nullable<long> rcuid { get; set; }

    public Nullable<System.DateTime> redt { get; set; }

}

}
