//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.UpdateMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoftwareRegistration
    {
        public int SoftwareRegistrationID { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string CompanyName { get; set; }
        public string BusinessType { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public string rcip { get; set; }
        public string reip { get; set; }
    }
}
