//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.Service.Update.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoftwareVersion
    {
        public int SoftwareVersionID { get; set; }
        public int GUIVersionMajor { get; set; }
        public int GUIVersionMinor { get; set; }
        public bool FilesDownloadsRequired { get; set; }
        public System.DateTime ReleaseDateTime { get; set; }
    }
}
