//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alit.Marker.Service.Update.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceRequestLog
    {
        public int ServiceRequestLogID { get; set; }
        public string CallingAPI { get; set; }
        public string Parameteres { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public string RequestBody { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public string ResponseBody { get; set; }
    }
}
